name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: 'Whether to update the playwright reference screenshots'
        required: false
        type: boolean
        default: false

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm turbo run build format typecheck lint test

  find-changed-apps:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.get-changed-apps.outputs.apps }}
    steps:
      # Setup
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: ./.github/actions/setup
      - name: Get Changed Apps
        id: get-changed-apps
        run: |
          APPS=$(pnpm turbo ls --output=json --affected | jq -c '.packages.items | map(select(.path | startswith("apps/")) | .name)')
          echo $APPS
          echo "apps=$APPS" >> $GITHUB_OUTPUT

  deploy:
    needs: [find-changed-apps]
    runs-on: ubuntu-latest
    if: ${{ needs.find-changed-apps.outputs.apps != '[]' }}
    strategy:
      matrix:
        app: ${{ fromJson(needs.find-changed-apps.outputs.apps) }}
    steps:
      # Setup
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup
      # Deploy
      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest
      - name: Link To Project
        working-directory: ./apps/${{ matrix.app }}
        run: vercel link --yes --repo --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ vars.TURBO_TEAM }}
      - name: Deploy To Vercel
        working-directory: ./apps/${{ matrix.app }}
        run: pnpm turbo deploy -- -- --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ vars.TURBO_TEAM }} ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}

  e2e:
    needs: [find-changed-apps, deploy]
    runs-on: windows-latest
    if: ${{ needs.find-changed-apps.outputs.apps != '[]' }}
    strategy:
      matrix:
        app: ${{ fromJson(needs.find-changed-apps.outputs.apps) }}
    steps:
      # Setup
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup
      # Browsers
      - name: Install Playwright Browsers
        working-directory: ./apps/${{ matrix.app }}
        run: pnpm exec playwright install --with-deps
      # Tests
      - name: Run Playwright tests
        working-directory: ./apps/${{ matrix.app }}
        env:
          BASE_URL: https://${{ matrix.app }}-git-${{ github.head_ref || github.ref_name }}-${{ vars.TURBO_TEAM }}.vercel.app
        run: pnpm turbo run e2e${{ inputs.update_snapshots && ':update' || '' }}
      # Optional: Update screenshots
      - name: Update Screenshots
        if: ${{ !failure() && inputs.update_snapshots }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "*/*.png"
          git commit -m "Update Screenshots"
          git push
      # Report
      - name: Publish Report
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-report-${{ matrix.app }}
          path: '**/apps/${{ matrix.app }}/playwright-report'
          retention-days: 30

  ci-successs:
    needs: [build, deploy, e2e]
    runs-on: ubuntu-latest
    steps:
      - run: echo Done!
